// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package crawler

// Injectors from wire.go:

func NewCrawlerWire() *CrawlerController {
	crawlerService := NewCrawlerService()
	crawlerController := NewCrawlerController(crawlerService)
	return crawlerController
}
